version: '3'

services:
  nextcloud:
    image: nextcloud:23-fpm-alpine
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - OBJECTSTORE_S3_HOST=aws
      - OBJECTSTORE_S3_PORT=4566
      - OBJECTSTORE_S3_USEPATH_STYLE=true
      - OBJECTSTORE_S3_BUCKET=nextcloud
      - OBJECTSTORE_S3_SSL=false
      - OBJECTSTORE_S3_KEY=x
      - OBJECTSTORE_S3_SECRET=x
      - OBJECTSTORE_S3_REGION=us-east-1
      - REDIS_HOST=redis
    volumes:
      - nextcloud:/var/www/html
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db:/var/lib/postgresql/data
  aws:
    image: localstack/localstack:0.13
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
  proxy:
    image: nginx:1.21-alpine
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html
      - certbot:/var/www/certbot/:ro
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  nextcloud-cron:
    image: nextcloud:23-fpm-alpine
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - postgres
      - redis
  certbot:
    image: certbot/certbot
    volumes:
      - certbot:/var/www/certbot/:rw

volumes:
  nextcloud:
  db:
  certbot: